site_name: Detran-DF

repo_name: "2025.1-DetranDF"
repo_url: "https://github.com/Requisitos-de-Software/2025.1-DetranDF.git"
site_url: "https://requisitos-de-software.github.io/2025.1-DetranDF/"

theme:
  name: material
  favicon: assets/detrandf-logo.png
  logo: assets/detrandf-logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Dark mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Light mode
      primary: indigo
      accent: indigo

markdown_extensions:
  - attr_list
  - tables

nav:
  - Início: index.md
  - Atas das Reuniões:
      - Reunião 1 - 04/04/2025: atas-reuniao/ata-1.md
      - Reunião 2 - 08/04/2025: atas-reuniao/ata-2.md
  - Apresentações:
      - Apresentação das Etapas:
          - Apresentação Etapa 1: Apresentações/Apresentação das Etapas/Apresentção1.md
          - Apresentação Etapa 2: Apresentações/Apresentação das Etapas/Apresentação2.md
          - Apresentação Etapa 3: Apresentações/Apresentação das Etapas/Apresentação3.md
      - Apresentação das Inspeções das Etapas:
          - Apresentação Inspeção da etapa 1: Apresentações/Apresentação das Inspeções das etapas/Apresentação-inpseção1.md
          - Apresentação Inspeção da etapa 2: Apresentações/Apresentação das Inspeções das etapas/Apresentação-inspeção2.md
          - Apresentação Inspeção da etapa 3: Apresentações/Apresentação das Inspeções das etapas/Apresentação-inspeção3.md
  - Planejamento:
      - Heatmap: planejamento/heatmap.md
      - Aplicativos Avaliados: planejamento/apps-avaliados.md
      - Aplicativo Selecionado: planejamento/AplicativoSelecionado.md
      - Ferramentas: planejamento/Ferramentas.md
      - Termo de uso: planejamento/termo-de-uso.md
      - Cronograma: planejamento/cronograma.md
      - Cronograma Executado: planejamento/Cronograma-executado.md
      - Metodologia: planejamento/metodologia.md
      - Rich Pictures: planejamento/Rich-picture.md
  - Elicitação:
      - Perfil do Usuário: Elicitação/Perfil-usuario.md
      - Personas: Elicitação/personas.md
      - Tecnicas de Elicitação:
          - Brainstorming: Elicitação/Tecnicas-de-elecitação/Brainstorming.md
          - Observação: Elicitação/Tecnicas-de-elecitação/Observação.md
          - Introspecção: Elicitação/Tecnicas-de-elecitação/Introspecção.md
          - Glossário: Elicitação/Tecnicas-de-elecitação/glossario.md
          - Requisitos Elicitados: Elicitação/Tecnicas-de-elecitação/requisitos-elicitados.md
      - Tecnicas de Priorização:
          - First thing First: Elicitação/tecnicas-de-priorização/First thing First.md
          - In or out: Elicitação/tecnicas-de-priorização/In or out.md
          - $100: Elicitação/tecnicas-de-priorização/$100.md
          - Moscow: Elicitação/tecnicas-de-priorização/moscow.md
  - Modelagem:
          - Cenários: modelagem/Cenários..md
          - Léxicos: modelagem/lexico.md
          - Casos de Uso: modelagem/caso-de-uso.md
          - Especificação Suplementar: modelagem/especificação-suplementar.md
  - Verificações:
      - Entrega 1:
          - Lista de Verificação:
              - Home: Verificações/Entrega 1/Lista-verificaçõa/home.md
              - Heatmap: Verificações/Entrega 1/Lista-verificaçõa/heatmap.md
              - Apps Avaliados: Verificações/Entrega 1/Lista-verificaçõa/apps-avalliados.md
              - App Selecionado: Verificações/Entrega 1/Lista-verificaçõa/app-selecionado.md
              - Termo de uso: Verificações/Entrega 1/Lista-verificaçõa/termodeuso.md
              - Ferramentas: Verificações/Entrega 1/Lista-verificaçõa/ferramentas.md
              - Cronograma: Verificações/Entrega 1/Lista-verificaçõa/cronograma.md
              - Rich picture: Verificações/Entrega 1/Lista-verificaçõa/rich-picture.md
              - Metodologia: Verificações/Entrega 1/Lista-verificaçõa/meotodologis.md
          - Verificação Nosso Grupo:
              - Home: Verificações/Entrega 1/Verificação-Nossogrupo/Home.md
              - Heatmap: Verificações/Entrega 1/Verificação-Nossogrupo/heatmap.md
              - Apps Avaliados: Verificações/Entrega 1/Verificação-Nossogrupo/apps-avaliados.md
              - App Selecionado: Verificações/Entrega 1/Verificação-Nossogrupo/app-selecionado.md
              - Termo de uso: Verificações/Entrega 1/Verificação-Nossogrupo/termodeuso.md
              - Ferramentas: Verificações/Entrega 1/Verificação-Nossogrupo/ferramentas.md
              - Cronograma: Verificações/Entrega 1/Verificação-Nossogrupo/cronograma.md
              - Rich picture: Verificações/Entrega 1/Verificação-Nossogrupo/rich-picture.md
              - Metodologia: Verificações/Entrega 1/Verificação-Nossogrupo/metodologia.md
          - Verificação Grupo +1:
              - Home: Verificações/Entrega 1/Verificaçã-grupo+1/Home.md
              - Heatmap: Verificações/Entrega 1/Verificaçã-grupo+1/heatmap.md
              - Apps Avaliados: Verificações/Entrega 1/Verificaçã-grupo+1/apps-avaliados.md
              - App Selecionado: Verificações/Entrega 1/Verificaçã-grupo+1/app-selecionado.md
              - Termo de uso: Verificações/Entrega 1/Verificaçã-grupo+1/termodeuso.md
              - Ferramentas: Verificações/Entrega 1/Verificaçã-grupo+1/ferramentas.md
              - Cronograma: Verificações/Entrega 1/Verificaçã-grupo+1/cronograma.md
              - Rich picture: Verificações/Entrega 1/Verificaçã-grupo+1/rich-picture.md
              - Metodologia: Verificações/Entrega 1/Verificaçã-grupo+1/metodologia.md
      - Entrega 2:
          - Lista de Verificação:
              - Perfil de Usuário: Verificações/Entrega 2/Lista-verificação/perfil-usuario.md
              - Personas: Verificações/Entrega 2/Lista-verificação/Personas.md
              - Brainstorming: Verificações/Entrega 2/Lista-verificação/Brainstorming.md
              - Observação: Verificações/Entrega 2/Lista-verificação/Observação.md
              - Introspecção: Verificações/Entrega 2/Lista-verificação/Introspecção.md
              - Pesquisa/Questionário: Verificações/Entrega 2/Lista-verificação/Questionario.md
              - Glossário: Verificações/Entrega 2/Lista-verificação/glossario.md
              - Verificação Elicitados: Verificações/Entrega 2/Lista-verificação/verificação.md
              - First thing First: Verificações/Entrega 2/Lista-verificação/First thing First.md
              - $100: Verificações/Entrega 2/Lista-verificação/$100.md
              - Moscow: Verificações/Entrega 2/Lista-verificação/moscow.md
              - Three Level Scale: Verificações/Entrega 2/Lista-verificação/ThreeLevelScale.md
              - In or Out: Verificações/Entrega 2/Lista-verificação/In or Out.md
          - Verificação Grupo +1:
              - Perfil de Usuário: Verificações/Entrega 2/verificação-Grupo+1/perfil-usuario.md
              - Observação: Verificações/Entrega 2/verificação-Grupo+1/Observação.md
              - Pesquisa/Questionário: Verificações/Entrega 2/verificação-Grupo+1/Questionario.md
              - Analise de Documentos: Verificações/Entrega 2/verificação-Grupo+1/glossario.md
              - Verificação Elicitados: Verificações/Entrega 2/verificação-Grupo+1/verficação.md
              - Moscow: Verificações/Entrega 2/verificação-Grupo+1/moscow.md
              - Análise de Interface: Verificações/Entrega 2/verificação-Grupo+1/analiseInterface.md
              - Quality Function Deployment: Verificações/Entrega 2/verificação-Grupo+1/quality.md
              - Three Level Scale: Verificações/Entrega 2/verificação-Grupo+1/ThreeLevelScale.md
              - In or Out: Verificações/Entrega 2/verificação-Grupo+1/In or Out.md
          - Verificação Nosso Grupo:
              - Perfil de Usuário: Verificações/Entrega 2/Verificação-nosso-grupo/perfil-usuario.md
              - Personas: Verificações/Entrega 2/Verificação-nosso-grupo/personas.md
              - Brainstorming: Verificações/Entrega 2/Verificação-nosso-grupo/Brainstorming.md
              - Observação: Verificações/Entrega 2/Verificação-nosso-grupo/Observação.md
              - Introspecção: Verificações/Entrega 2/Verificação-nosso-grupo/Introspecção.md
              - Glossário: Verificações/Entrega 2/Verificação-nosso-grupo/glossario.md
              - Verificação Elicitados: Verificações/Entrega 2/Verificação-nosso-grupo/verificação.md
              - First thing First: Verificações/Entrega 2/Verificação-nosso-grupo/First thing First.md
              - $100: Verificações/Entrega 2/Verificação-nosso-grupo/100.md
              - Moscow: Verificações/Entrega 2/Verificação-nosso-grupo/moscow.md
              - In or Out: Verificações/Entrega 2/Verificação-nosso-grupo/In or Out.md
      - Entrega 3:
          - Lista de Verificação:
              - Cenários: Verificações/Entrega 3/Lista-verificação/cenarios.md
              - Léxicos: Verificações/Entrega 3/Lista-verificação/lexicos.md
              - Casos de Uso: Verificações/Entrega 3/Lista-verificação/caso-de-uso.md
              - Especificação Suplementar: Verificações/Entrega 3/Lista-verificação/especificação-suplementar.md
          - Verificação Grupo +1:
             - Cenários: Verificações/Entrega 3/grupo+1/cenários.md
             - Léxicos: Verificações/Entrega 3/grupo+1/lexicos.md
             - Casos de Uso: Verificações/Entrega 3/grupo+1/caso-de-uso.md
             - Especificação Suplementar: Verificações/Entrega 3/grupo+1/especificação-suplementar.md
          - Verificação Nosso Grupo:
             - Cenários: Verificações/Entrega 3/nossogrupo/cenarios.md
             - Léxicos: Verificações/Entrega 3/nossogrupo/lexicos.md
             - Casos de Uso: Verificações/Entrega 3/nossogrupo/caso-de-uso.md
             - Especificação Suplementar: Verificações/Entrega 3/nossogrupo/especificação-suplementar.md
              
