site_name: Detran-DF

repo_name: "2025.1-DetranDF"
repo_url: "https://github.com/Requisitos-de-Software/2025.1-DetranDF.git"
site_url: "https://requisitos-de-software.github.io/2025.1-DetranDF/"

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Dark mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Light mode
      primary: indigo
      accent: indigo

markdown_extensions:
  - attr_list

extra_css:
  - css/custom.css

nav:
  - Início: index.md
  - Planejamento:
      - Aplicativo Selecionado: planejamento/AplicativoSelecionado.md
      - Termo de uso: planejamento/termo-de-uso.md
      - Cronograma: planejamento/cronograma.md
      - Metodologia: planejamento/metodologia.md
  - Atas das Reuniões:
      - Reunião 1 - 04/04/2025: atas-reuniao/ata-1.md
      - Reunião 2 - 08/04/2025: atas-reuniao/ata-2.md
