site_name: Detran-DF

repo_name: "2025.1-DetranDF"
repo_url: "https://github.com/Requisitos-de-Software/2025.1-DetranDF.git"
site_url: "https://requisitos-de-software.github.io/2025.1-DetranDF/"

theme:
  name: material
  favicon: assets/detrandf-logo.png
  logo: assets/detrandf-logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Dark mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Light mode
      primary: indigo
      accent: indigo

markdown_extensions:
  - attr_list
  - tables

nav:
  - Início: index.md
  - Atas das Reuniões:
      - Reunião 1 - 04/04/2025: atas-reuniao/ata-1.md
      - Reunião 2 - 08/04/2025: atas-reuniao/ata-2.md
  - Apresentações:
      - Apresentação 1: Apresentações/Apresentção1.md
  - Planejamento:
      - Heatmap: planejamento/heatmap.md
      - Aplicativos Avaliados: planejamento/apps-avaliados.md
      - Aplicativo Selecionado: planejamento/AplicativoSelecionado.md
      - Ferramentas: planejamento/Ferramentas.md
      - Termo de uso: planejamento/termo-de-uso.md
      - Cronograma: planejamento/cronograma.md
      - Cronograma Executado: planejamento/Cronograma-executado.md
      - Metodologia: planejamento/metodologia.md
      - Rich Pictures: planejamento/Rich-picture.md
  - Verificações:
      - Entrega 1:
          - Verificação Nosso Grupo: Verificações/Entrega 1/Verificação-NossoGrupo.md
          - Verificação Grupo +1: Verificações/Entrega 1/Verificação-Grupo+1.md
